#!/usr/bin/env python3

import tomllib

with open("preferences.toml", "rb") as f:
    data = tomllib.load(f)

typeCasts = {
    "BOOL": "boolValue",
    "int": "intValue",
    "double": "doubleValue",
    "float": "floatValue",
    "NSInteger": "integerValue"
}

class Preference:
    def __init__(self, name, type, default):
        self.name = name
        self.type = type
        self.default = default

    def __str__(self):
        return f"{self.name} {self.type} {self.default}"

preferences = []
for table in data:
    items = data[table]
    preferences.append(Preference(items["name"], items["type"], items["default"]))

prefVariables = []
prefLoads = []

for pref in preferences:
    value = f"[[preferences objectForKey:@\"{pref.name}\"];"
    if typeCasts[pref.type]:
        value = f"[[preferences objectForKey:@\"{pref.name}\"] {typeCasts[pref.type]}];"

    prefVariables.append(f"static {pref.type} {pref.name} = {pref.default};")
    prefLoads.append(f"{pref.name} = {value}")


with open("Preferences/Preferences.h", "w") as f:
    f.truncate(0)

    f.write("""// THIS FILE IS AUTOGENERATED BY codegen.py
// DO NOT MODIFY THIS FILE DIRECTLY. YOUR CHANGES WILL BE OVERWRITTEN.\n\n""")

    f.write("""static NSString* const PreferencesIdentifier = @"com.example.REPLACE_THIS_TWEAKNAME.preferences";
static NSString* const PreferencesReloadNotification = @"com.example.REPLACE_THIS_TWEAKNAME.preferences.reload";\n\n""")

    for pref in prefVariables:
        f.write(pref)
        f.write("\n")

    f.write("""\nstatic void LoadPreferences() {
    NSUserDefaults* preferences = [[NSUserDefaults alloc] initWithSuiteName:PreferencesIdentifier];
    if (!preferences) return;\n
    """)

    for pref in prefLoads:
        f.write(pref)
        f.write("\n")

    f.write("}\n")
