// THIS FILE IS AUTOGENERATED BY codegen.py
// DO NOT MODIFY THIS FILE DIRECTLY. YOUR CHANGES WILL BE OVERWRITTEN.

static NSString* const PreferencesIdentifier = @"com.cOOlKiddBluedudd.nineunlockreimagined.preferences";
static NSString* const PreferencesReloadNotification = @"com.cOOlKiddBlueDudd.Nineunlockreimagined.preferences.reload";

static BOOL EnabledPreference = NO;

static void LoadPreferences() {
    NSUserDefaults* preferences = [[NSUserDefaults alloc] initWithSuiteName:PreferencesIdentifier];
    if (!preferences) return;

    EnabledPreference = [[preferences objectForKey:@"EnabledPreference"] boolValue];
}
